### ISSUE TITLE
Adding Public Domain to licenses

### ISSUE THREAD

**Issue by bitnapper** [gnotaras/wordpress-creative-commons-configurator#4]
The copyright on some works is expired which means there is no copyright at all. CC0 means releasing works under terms very much like Public Domain (depending on the country of first releasy or creation). For most people CC0 seems to be ok but I'd like to mark files which are already under PD as such. So I think adding PD under licenses would be great.

**Comment by gnotaras** [comment]
Good point about expired copyright. I'll be doing some more research about this and check what kind of generic text could be used in the templates. Any suggestions or pointers are very much appreciated.

**Comment by gnotaras** [comment]
Hi,

I did some more research about _Public Domain_ and the concerns I wrote about in the email still stand. Due to the differences in legislation around the world it is very possible that a statement about _Public Domain_ could lead to misinterpretation and misunderstandings. Therefore, it is generally advised to use a license that gives as many rights to the user as possible, like it happens with [CC0](https://creativecommons.org/publicdomain/zero/1.0/), which is supported by _CC-Configurator_ out of the box, and also other similar licenses like [Unlicense](http://unlicense.org/) or [WTFPL](http://www.wtfpl.net/).

I already mentioned it in the email, but I also write it here again so it can be seen by other users who might be having a similar feature request, that [a custom license can be added](http://www.codetrax.org/projects/wp-cc-configurator/wiki/Customization) very easily in _CC-Configurator_ as shown in the examples on the wiki.

The same concerns also still stand for *expired copyrights* as it might be necessary to specify the jurisdiction in which the statement is applicable. For example, Project Gutemberg has stopped mentioning _Public Domain_ and, instead, uses the [Project Gutemberg License](http://www.gutenberg.org/wiki/Gutenberg:The_Project_Gutenberg_License) for the book distribution due to the possibility of misinterpretation of a statement about Public Domain.

This is quite complicated and possibly needs to be further discussed with people having legal knowledge.

My final thoughts are that I'd rather leave the addition of _Public Domain_ related statements to the end user. However, what I can do is add a few more examples about how to add such custom statements/licenses in _CC-Configurator_.

Of course, I'm always open to ideas about alternative ways to resolve this. If you happen to know of a text template that is used by convention in such cases, I'd be happy to add it in the default licenses.

I'll leave this issue open for the time being. Hopefully we'll get more comments and suggestions about this in the future.

Kind Regards,
George

**Comment by gnotaras** [comment]
Hi @bitnapper,

I have added sample code in the wiki about [how to include a Public Domain statement](http://www.codetrax.org/projects/wp-cc-configurator/wiki/Customization#Example-3-Public-Domain-statement) (should be customized according to the country's legislation) in the list of available licenses.

According to my research there is much legal complexity around such a statement as it depends on each country's laws and/or other conditions. Therefore, it's almost impossible to find a template of a statement that fits in all cases, so this has to be done manually by the user.

So, as long as a generic statement that has full effect worldwide does not exist, the above approach should resolve this issue. However, further feedback is welcome and much appreciated.

Kind Regards,
George
