### ISSUE TITLE
Plugin Questions

### ISSUE THREAD

**Issue by Falenos** [gnotaras/wordpress-creative-commons-configurator#9]
Hi George,

I am building a group blog (και μιλώ Ελληνικά αλλά για να το διαβάζουν όλοι το Αγγλικό).
It's not online though, still configuring it. The goal is to have authors and comics designers collaborate in fiction stories. The result if all goes well is the creation of eBooks, fanzines or graphic novels with free donation model (splitted between the contributors)

Need some infos about some functions of the plugin:

1. In some posts I have text that I want to protect, but the images are not mine (from the web somewhere). Is it ok to use the licenses, or do I have to specify if its only for the text. If that’s the case how can I do that?

2. Who owns the rights? The website or the authors? If its the authors and they use alias (public name in options) are they still protected?

3. The comics guys will create images posts. Are they covered (cause they upload them)?

4. Is there any way to express that the pictures are covered by the license and not the text (and vice versa)

I understand these questions are about legalities and not functionality, but I would really appreciate your opinion on this.

Awesome plugin by the way, saved me from headaches

**Comment by gnotaras** [comment]
Hello @Falenos (Γεια σου φίλε μου, σ' ευχαριστώ για τα καλά σου λόγια),

Please let me write a disclaimer note before my actual reply: I have no knowledge of laws and everything I write below is just the result of personal research. It does not constitute legal advice in any way. A professional should be asked about the legal details.

> In some posts I have text that I want to protect, but the images are not mine (from the web somewhere). Is it ok to use the licenses, or do I have to specify if its only for the text. If that’s the case how can I do that?

I'd suggest the following:

1. Modify the CC license text templates and include the phrase: *Unless otherwise expressly stated, this work is licenses under a ...*. This can be done with filtering. I'll add an extra example in the [wiki page about customization](http://www.codetrax.org/projects/wp-cc-configurator/wiki/Customization) and write another comment at some later time about the technical details of this.
1. Either add specific licensing information in the caption of each image or, if it fits the needs, you can use the `[license]` [short code](http://www.codetrax.org/projects/wp-cc-configurator/wiki/Features#License-Shortcode) provided by the plugin in order to add licensing information for specific parts of the post.

> Who owns the rights? The website or the authors? If its the authors and they use alias (public name in options) are they still protected?

> The comics guys will create images posts. Are they covered (cause they upload them)?

I assume there is no general rule about this. It is up to the service (website) to publish the legal terms and conditions that govern user contributions. Perhaps, doing some research about how it is done in similar collaborative projects might be a good idea.

> Is there any way to express that the pictures are covered by the license and not the text (and vice versa)

I think that modifying the license text templates of the plugin and adding a legal section on the web site which would clarify these things would be a good start.

I'm not sure if the above have been helpful (I hope yes), but in any case a professional's opinion might be necessary.

I'll let you know of the extra customization example I mentioned earlier.

Σ'ευχαριστώ και πάλι.

Kind Regards,
George

**Comment by gnotaras** [comment]
An extra [customization example](http://www.codetrax.org/projects/wp-cc-configurator/wiki/Customization#Customize-the-text-templates-of-a-single-license-or-of-a-group-of-licenses) with informative comments has been added. If you need more help, please feel free to ask.

BTW, there might be cases in which licensing information might be easier to hardcode into the relevant sections of the theme templates than using a plugin like cc-configurator. It really depends on the project and the case. This plugin offers much flexibility, but this is always limited by many factors.

I'm going to leave the topic open for further user feedback about this.

George

**Comment by Falenos** [comment]
@gnotaras (είσαι παλικάρι) feel free to check the blog, I will publish it by Friday http://sushiworldwars.gr 

Good news is that I kinda get the idea of the solution

"Either add specific licensing information in the caption of each image or, if it fits the needs, you can use the [license] short code provided by the plugin in order to add licensing information for specific parts of the post."
This is a decent solution in my case I believe. But It's pretty manual work so I like your other solution better.

Bad news, I am not a developer (so I don't know anchors and filters) and this is my first attempt in creating a website. By this I mean that it will take me a while to experiment and learn, so i might be back in a later time about this

"I assume there is no general rule about this. It is up to the service (website) to publish the legal terms and conditions that govern user contributions. Perhaps, doing some research about how it is done in similar collaborative projects might be a good idea."
Thanks, will do that

Just one question about modifying the CC license and include the phrase: Unless otherwise expressly stated, this work is licensed under a...
By this phrase you mean that (in case the text is mine and the image isn't):
1. The images are already property of someone else and the phrase makes my claim invalid for them?
2.Or that I should mention in the image captions that this content is excluded?
Just need to understand your logic better

Many thanks for the fast support

**Comment by gnotaras** [comment]
Hi,

The web site is not accessible at this time. but I'll check it once it is launched.

> this is my first attempt in creating a website. By this I mean that it will take me a while to experiment and learn, so i might be back in a later time about this

If you need any help with the customization of the plugin output, feel free to open an issue on this issue tracker. Please note there are times that it takes a while before I respond. :)

You can copy-paste the examples of the wiki page in your theme's `functions.php` file and customize the text of the template as you see fit. It may sound complicated, but it's really that simple.

> Just one question about modifying the CC license and include the phrase: Unless otherwise expressly stated, this work is licensed under a...
> By this phrase you mean that (in case the text is mine and the image isn't):
> 1. The images are already property of someone else and the phrase makes my claim invalid for them?
> 2.Or that I should mention in the image captions that this content is excluded?
Just need to understand your logic better

The logic of my suggestion is that the visitor or potential user should consider the published content on the page licensed under the license that exists at the end of the page, except for those parts of the content, eg images, for which different licensing is indicated, eg int he caption or within the page.

However, I'd like to add note to all of this. People generally tend to dislike legal stuff, so I'd suggest to not overdo it with the licensing info. ;)

George

**Comment by dx486** [comment]
Hello,

To have translated licence information below posts, your solution is mentioned [here ](https://wordpress.org/support/topic/feature-request-define-license-language-for-links)as below:

> The solution I'm thinking of is the availability of a filter hook, which can be used to manually append the deed.COUNTRY_CODE part to the license URLs.

Could you please tell me how can I apply this solution? I have no idea.

Regards

**Comment by gnotaras** [comment]
Hi @dx486,

Thank you for your question. For the sake of better organization I'd appreciate if your had opened a new issue. :)

Nevertheless, you are absolutely right. An example of this particular customization is missing. Please check [how to customize the license URL](http://www.codetrax.org/projects/wp-cc-configurator/wiki/Customization#Customize-the-license-URL).

George

**Comment by gnotaras** [comment]
I'm going to close this issue now. Thanks all for your feedback. If you have more questions, please feel free to open a new ticket.

George
